export enum Icons {
    CALENDAR = '/icons/calendar.svg',
    CALL = '/icons/call.svg',
    CAMERA = '/icons/camera.svg',
    EDIT = '/icons/edit.svg',
    FACEBOOK = '/icons/facebook.svg',
    FAST_DELIVERY = '/icons/fast-delivery.svg',
    HEART = '/icons/heart.svg',
    INSTAGRAM = '/icons/instagram.svg',
    LOCK = '/icons/lock.svg',
    MAIl = '/icons/mail.svg',
    MONEY = '/icons/money.svg',
    SEARCH = '/icons/search.svg',
    SHOPPING_BAG = '/icons/shopping-bag.svg',
    STORE = '/icons/store.svg',
    TICKET_PERCENT = '/icons/ticket-percent.svg',
    USER_CIRCLE = '/icons/user-circle.svg',
    YOUTUBE = '/icons/youtube.svg',
}